version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  server:
    image: karamveer2000/recipe-app:latest
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
