version: '3.9'

services:
  server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   postgres-data:
